In [10]:
import numpy as np

arreglo = np.array([1,2,3,4,5,6])
arreglo2 = np.arange(1,10)
arreglo3 = [1,2,3,4,5,6]
print(arreglo2)
print(arreglo2[1])
print(arreglo3)
print(arreglo3[1])


[1 2 3 4 5 6 7 8 9]
2
[1, 2, 3, 4, 5, 6]
2


In [11]:
print(arreglo2)
print(arreglo2[1])
arreglo2[1] = 100
print(arreglo2)
print('*----')
print(arreglo3)
print(arreglo3[1])
arreglo3[1] = 100
print(arreglo3)

[1 2 3 4 5 6 7 8 9]
2
[  1 100   3   4   5   6   7   8   9]
*----
[1, 2, 3, 4, 5, 6]
2
[1, 100, 3, 4, 5, 6]


In [27]:
a1D = np.array([1, 2, 3, 4])
print(a1D)
print("--")
a2D = np.array([[1, 2], [3, 4]])
print(a2D)
print("--")
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a3D)

[1 2 3 4]
--
[[1 2]
 [3 4]]
--
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
""" 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
 """
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [44]:
a = np.array([1, 2, 3])
print(a.dtype)
b = np.array([127, 128, 129])
print(b.dtype)

c = a + b

print(c)

int32
int32
[128 130 132]


In [57]:
import numpy as np

a = np.array([1, 2, 3])
a2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a.dtype)
print(a2D.dtype)

c = a + a2D

print(c)


int32
int32


ValueError: operands could not be broadcast together with shapes (3,) (2,4) 

In [74]:
import numpy as np

a = np.array([1, 2, 3])
a2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


# Reshape 
a2 = np.arange(6).reshape((3, 2))
a2



array([[0, 1],
       [2, 3],
       [4, 5]])

In [47]:
a = np.diag([1, 2, 3])
print(a.dtype)
b = np.array([127, 128, 129])
print(b.dtype)

c = a + b

print(c)

int32
int32
[[128 128 129]
 [127 130 129]
 [127 128 132]]
